### ISSUE TITLE
[Doc]: invalid doc link to install 

### ISSUE THREAD

**Issue by shanshanying** [oceanbase/odc-doc#2]
### Description

<img width="1182" alt="image" src="https://github.com/oceanbase/odc-doc/assets/111829739/3be7603f-123b-4b5f-afe5-91563d72d14b">

### Documentation links

https://github.com/oceanbase/odc-doc/blob/V4.2.0/en-US/700.client-odc-user-guide/100.client-odc-install-odc.md

**Comment by yizhouxw** [comment]
thanks for report, the en-US version document is still in translating, will comming soon
